services:
  web:
    image: ${REGISTRY}/curriculum-vitae/web:${IMAGE_TAG}
    build:
      context: ../
      dockerfile: ./environments/web/Dockerfile

  ngix:
    image: ${REGISTRY}/curriculum-vitae/nginx:${IMAGE_TAG}
    build:
      context: ./nginx
