version: "2.4"

services:
  web:
    image: ${REGISTRY}/curriculum-vitae/web:${IMAGE_TAG}
    build:
      context: ../
      dockerfile: ./environments/web/Dockerfile
      x-bake:
        platforms:
          - linux/arm64

  nginx:
    image: ${REGISTRY}/curriculum-vitae/nginx:${IMAGE_TAG}
    build:
      context: ./nginx
      x-bake:
        platforms:
          - linux/arm64
