export const NOTIFICATION_TYPE_BASIC = "NOTIFICATION_TYPE_BASIC";
export const NOTIFICATION_TYPE_BASIC_DELAY_TIME = 200;
export const NOTIFICATION_TYPE_BASIC_DISPLAY_TIME = 2000;
export const NOTIFICATION_TYPE_BASIC_TRANSITION_TIME = 500;
