export const NOTIFICATION_TYPE_BASIC = "NOTIFICATION_TYPE_BASIC";
export const NOTIFICATION_TYPE_BASIC_DELAY_TIME = 200;
export const NOTIFICATION_TYPE_BASIC_DISPLAY_TIME = 2000;
export const NOTIFICATION_TYPE_BASIC_TRANSITION_TIME = 500;

export const NOTIFICATION_TYPE_WARNING = "NOTIFICATION_TYPE_WARNING";
export const NOTIFICATION_TYPE_WARNING_DELAY_TIME = 200;
export const NOTIFICATION_TYPE_WARNING_DISPLAY_TIME = 2000;
export const NOTIFICATION_TYPE_WARNING_TRANSITION_TIME = 500;
