name: Terminate production

on:
  workflow_dispatch:
    tags:
      - "v*.*.*"

env:
  PROJECT: curriculum-vitae
  ENV: production
  AWS_REGION: ap-southeast-1 # set this to your preferred AWS region, e.g. us-west-1

jobs:
  deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 0.12.29

      - name: Terraform init
        working-directory: ./provision/production
        env:
          STATE: ${{ PROJECT }}/${{ env.ENV }}/${{ github.ref_name }}/terraform.tfstate
        run: terraform init -backend-config "key=$STATE" -force-copy -input=false

      - name: Terraform plan destroy
        working-directory: ./provision/production
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          VERSION: ${{ github.ref_name }}
        run: terraform plan -destroy -var="app_version=$VERSION" -var="registry=$ECR_REGISTRY"

      - name: Terraform destroy
        working-directory: ./provision/production
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          VERSION: ${{ github.ref_name }}
        run: terraform destroy -auto-approve -var="app_version=$VERSION" -var="registry=$ECR_REGISTRY"
